version: '2'

services:
  image-match:
    build: .
    volumes:
      - .:/usr/src/app/
  elasticsearch:
    image: elasticsearch
  docs:
    image: nginx
    ports:
      - '40080:80'
    volumes:
      - ./docs/build/html:/usr/share/nginx/html
